### PR TITLE
solves User is rate-limited by GitHub (issue324)

### PR DESCRIPTION
**Pull request by Swastik19Nit**
## Related Issue
Encountering the "Data is NULL. User is rate-limited by GitHub" error for some usernames.

## Description
#324 

## Type of PR

- [ X] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
image
image

## Checklist:
- [X ] I have performed a self-review of my code
- [X ] I have read and followed the Contribution Guidelines.
- [X ] I have tested the changes thoroughly before submitting this pull request.
- [ X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
The current code checks if userData.name is null or empty to determine if the user is rate-limited. However, this might not be the most reliable method, as some users might genuinely have no name set on their GitHub profile. So it should be changed to userData.username.

### CODE REVIEW

**Comment by ashutosh-rath02** [comment]
Thank you for submitting your pull request! 🙌 We'll review it as soon as possible. In the meantime, please ensure that your changes align with our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md). If there are any specific instructions or feedback regarding your PR, we'll provide them here. Thanks again for your contribution! 😊

**Comment by Swastik19Nit** [comment]
@ashutosh-rath02

**Comment by Swastik19Nit** [comment]
@ashutosh-rath02 i dont know whether this pull request is actually related to this issue or not but there is one problem we are encountering "Data is NULL. User is rate-limited by GitHub" error for some usernames. So should i raise an issue for this first?

**Comment by ashutosh-rath02** [comment]
@dhairyathedev

**Comment by dhairyathedev** [comment]
Hey @Swastik19Nit,

#319 is not related to this PR.

But, nice catch! You can merge this PR @ashutosh-rath02

**Review by dhairyathedev — APPROVED** [review]

**Comment by ashutosh-rath02** [comment]
@Swastik19Nit raise an issue so that your PR gets counted under GSSoC

**Review by ashutosh-rath02 — COMMENTED** [review]
LGTM

**Pull request merged**
