### PR TITLE
Added the floating navbar to go up and down on scroll

### PR DESCRIPTION
**Pull request by Utsavladia**
## Related Issue #414 
[Cite any related issue(s) this pull request addresses. If none, simply state “None”]

## Description

https://github.com/user-attachments/assets/12c9e4aa-8644-4ecf-ad89-45f3c281c4e1

[Please include a brief description of the changes or features added]

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by ashutosh-rath02** [comment]
Thank you for submitting your pull request! 🙌 We'll review it as soon as possible. In the meantime, please ensure that your changes align with our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md). If there are any specific instructions or feedback regarding your PR, we'll provide them here. Thanks again for your contribution! 😊

**Comment by Utsavladia** [comment]
@ashutosh-rath02 
error is related to useSearchParams right ??
we need to wrap the Home in suspence with fallback loading to fix it

**Comment by Utsavladia** [comment]
@ashutosh-rath02 
Kindly reivew this I resolved the conflicts

**Review by ashutosh-rath02 — CHANGES_REQUESTED** [review]
Why have you changed the async function here?

**Pull request closed without merging**
