### PR TITLE
Moving border Button

### PR DESCRIPTION
**Pull request by Rohitha-pudu**
#204 

Added border animation to the button

## Type of PR

- [ ] Bug fix
- [x ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

image

## Checklist:
- [ x] I have performed a self-review of my code
- [ x] I have read and followed the Contribution Guidelines.
- [ x] I have tested the changes thoroughly before submitting this pull request.
- [ x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by ashutosh-rath02** [comment]
Thank you for submitting your pull request! 🙌 We'll review it as soon as possible. In the meantime, please ensure that your changes align with our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md). If there are any specific instructions or feedback regarding your PR, we'll provide them here. Thanks again for your contribution! 😊

**Comment by Rohitha-pudu** [comment]
Assign?

**Comment by Rohitha-pudu** [comment]
> u forgot to Assign?

**Review by ashutosh-rath02 — COMMENTED** [review]
LGTM

**Pull request merged**
