### PR TITLE
fixed: The "images.domains" configuration is deprecated. Please use "images.remotePatterns" configuration instead.

### LINKED ISSUE #328: [Bug]: The "images.domains" configuration is deprecated. Please use "images.remotePatterns" configuration instead.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This error occurs in the development because, the `next.config.js` is using deprecated image configuration.

### Expected behavior

Next.js image configuration needs to be changed to the latest configuration.

### Add ScreenShots

Screenshot 2024-06-27 at 3 49 42 PM

### On which device are you experiencing this bug?

_No response_

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by dhairyathedev**
Fixes #328

### CODE REVIEW

**Comment by ashutosh-rath02** [comment]
Thank you for submitting your pull request! 🙌 We'll review it as soon as possible. In the meantime, please ensure that your changes align with our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md). If there are any specific instructions or feedback regarding your PR, we'll provide them here. Thanks again for your contribution! 😊

**Comment by dhairyathedev** [comment]
> Hey @dhairyathedev can you add path so that our images are not misused. We cannot directly whitelist our images for any path else someone may use it from our upstash account.

I guess we are not using Upstash anymore.

**Comment by ashutosh-rath02** [comment]
Be it upstash be it supa, whitelisting the images domains can be mis-used by others to use the links.

**Comment by dhairyathedev** [comment]
> Be it upstash be it supa, whitelisting the images domains can be mis-used by others to use the links. We are using images from cloudinary that can mis-used if we directly allow, better provide some path of our website

Issue resolved as discussed on Discord

**Pull request merged**
