### PR TITLE
Feat/391

### LINKED ISSUE #391: [Feature Request]: AI-Limit
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I am willing to add a limit to the usage of AI.
User can generate the cover letter for 2 times per day.

### Use Case

To limit the usage of Gemini API.

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Sid-80**
## Related Issue
resolves #391 

## Description
Added a limit to the use of AI

## Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

https://github.com/user-attachments/assets/83775982-3769-4828-a997-ff3678ea0b3f

https://github.com/user-attachments/assets/623951b3-c429-44d6-b85a-9cc2d3e29ff9

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by ashutosh-rath02** [comment]
Thank you for submitting your pull request! 🙌 We'll review it as soon as possible. In the meantime, please ensure that your changes align with our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md). If there are any specific instructions or feedback regarding your PR, we'll provide them here. Thanks again for your contribution! 😊

**Comment by Sid-80** [comment]
@ashutosh-rath02 PR is ready to Merge🚀

**Comment by ashutosh-rath02** [comment]
@Sid-80 you have to update the README for the new query that we have to insert

**Comment by Sid-80** [comment]
> @Sid-80 you have to update the README for the new query that we have to insert

Updated

**Comment by Sid-80** [comment]
image

**Review by ashutosh-rath02 — APPROVED** [review]
LGTM🌴Merging...

**Pull request merged**
