### PR TITLE
chore: improved github data fetching performance

### LINKED ISSUE #312: chore: Improve resume page loading performance
### Issue
It takes more than 30 seconds to load the resume page, which worsens the user experience.

Please assign this issue to me.

### PR DESCRIPTION
**Pull request by dhairyathedev**
Fixes #312

### CODE REVIEW

**Comment by ashutosh-rath02** [comment]
Thank you for submitting your pull request! 🙌 We'll review it as soon as possible. In the meantime, please ensure that your changes align with our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md). If there are any specific instructions or feedback regarding your PR, we'll provide them here. Thanks again for your contribution! 😊

**Comment by ashutosh-rath02** [comment]
Hey @dhairyathedev as this will be a change in our API fetching method, will you please provide a detailed documentation on how you made the changes, how to view the fetched data in apollo and all for the new users to get accustomed to it. Attaching a video will be great along with the docs. You can create a new issue and new PR.

**Comment by dhairyathedev** [comment]
Removed `@apollo/client`, now it only takes around 5-7 seconds to load the resume page.

**Comment by dhairyathedev** [comment]
> Hey @dhairyathedev as this will be a change in our API fetching method, will you please provide a detailed documentation on how you made the changes, how to view the fetched data in apollo and all for the new users to get accustomed to it. Attaching a video will be great along with the docs. You can create a new issue and new PR.

Hey @ashutosh-rath02 ,
now I have switched the codebase to traditional graphql api call, I don't think we need a documentation/video for this. What do you say?

**Comment by ashutosh-rath02** [comment]
Not in the readme file, you can drop the changes you made here in the PR. I like the PRs to be self defining.

**Comment by dhairyathedev** [comment]
## Changelog

- Removed multiple redundant REST API calls affecting performance into a single GraphQL query.
- Removed caching since it was unnecessary.
- Commented out the old resume template code,  which needs a refactor to align with the latest data fetching utility functions. This change is necessary to prevent build failures in the production version.

**Review by ashutosh-rath02 — COMMENTED** [review]
LGTM

**Pull request merged**
