### PR TITLE
Validation added for searching for a github username

### PR DESCRIPTION
**Pull request by kshavp**
This PR is regarding issue #53.

# Description

I have used a regex that matches the actual github username validation criteria to fulfill our validation. Instead of indulging into an actual post request and return a 404, I've considered this approach to minimize extra operations and time consumption.

# Files Modified

components/Form.tsx : Added a regex and used an if statement.

## Working

The button would not send the post request as it should if the provided username seems to not follow the validation criteria. This is kept minimal until further guidance provided by the repository owner.

# [UPDATED]

# Description

Previously regex that matched the actual github username validation criteria to fulfill our validation. Now if the validation fails, a new toast appears regarding the failed validation. 

# Files Modified

components/Form.tsx : Added made a call to toast function.

## Working

Toast pops up for invalid username format as shown in the attached media.

image

### CODE REVIEW

**Comment by ashutosh-rath02** [comment]
Hey @kshavp can you provide me some of it's use cases?

**Comment by kshavp** [comment]
Sure, refer the provided media as well the context composed below

### 1. Valid Username Entry:

Scenario: User enters a valid GitHub username containing only alphanumeric characters.
Expected Behavior: The form submission proceeds successfully, allowing the user to generate the resume.


### 2. Invalid Username with Special Characters:

Scenario: User enters a username containing special characters such as @, #, $, etc.
Expected Behavior: The submit button does not facilitate the form to send a post request.


### 3.Invalid Username (Empty):

Scenario: User leaves the username field empty.
Expected Behavior: The submit button does not facilitate the form to send a post request.


###4.Invalid Username with Whitespace:

Scenario: User enters whitespace characters as the username.
Expected Behavior: The submit button does not facilitate the form to send a post request.


https://github.com/ashutosh-rath02/git-re/assets/95236968/10e4abba-6f2b-41ed-ba7b-3e9b3091b1c7

**Comment by ashutosh-rath02** [comment]
Use a toast maybe it will look good. Username may have hyphens but not following it or consecutive multiple hyphens, have you taken that into consideration?

**Comment by kshavp** [comment]
Yes the hyphens are under consideration. I'll update with the toast component soon.

**Comment by ashutosh-rath02** [comment]
How is it coming @kshavp ?

**Comment by kshavp** [comment]
Hey @ashutosh-rath02 , it's almost ready, just about to update the PR.

**Comment by ashutosh-rath02** [comment]
@kshavp A small video will do to check

**Comment by kshavp** [comment]
Sure, have a look.

https://github.com/ashutosh-rath02/git-re/assets/95236968/48fee6df-fa46-44e0-84a5-9e149e88095b

**Comment by ashutosh-rath02** [comment]
LGTM🤺

**Comment by ashutosh-rath02** [comment]
@all-contributors please add @kshavp for code

**Pull request merged**
