### PR TITLE
Added error checking mechanisms

### PR DESCRIPTION
**Pull request by IbrahimDev00**
1. Added error checking in "resume" page to ensure the username fetched is returned and is valid.
2. Added a custom error page to display the error and redirect the user to the home page. The errors caught are :
 - Page not found error
 - API limit reached error
 - Access denied error (if the user does not authenticate, the third party app to access their profile)
3. Added a global error page, to catch all the above mentioned errors on a global scale.
4. Added a custom 404 page.

### CODE REVIEW

**Comment by ashutosh-rath02** [comment]
@IbrahimDev00 Can you please provide a short video demonstrating it?

**Comment by ashutosh-rath02** [comment]
Hey @IbrahimDev00 , you can check out discussion for a new feature discussion https://github.com/ashutosh-rath02/git-re/discussions/133

**Comment by IbrahimDev00** [comment]
Hello @ashutosh-rath02 im facing a problem with supabase :
image
Could you please tell me how to rectify this so I can send you a working video

**Comment by IbrahimDev00** [comment]
https://github.com/ashutosh-rath02/git-re/assets/147825977/02c3ce6e-5d71-4d19-9b56-e24277b28871

**Comment by ashutosh-rath02** [comment]
please remove changes from .env.example

**Comment by ashutosh-rath02** [comment]
@all-contributors please add @IbrahimDev00 for code

**Comment by ashutosh-rath02** [comment]
@IbrahimDev00 Did you open any issue for this?

**Pull request merged**
