### PR TITLE
feat: 404 not found page redesigned

### PR DESCRIPTION
**Pull request by RamakrushnaBiswal**
## Related Issue
#302 solved
## Description
404 not found page added

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
image

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by ashutosh-rath02** [comment]
Thank you for submitting your pull request! 🙌 We'll review it as soon as possible. In the meantime, please ensure that your changes align with our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md). If there are any specific instructions or feedback regarding your PR, we'll provide them here. Thanks again for your contribution! 😊

**Comment by RamakrushnaBiswal** [comment]
hi @ashutosh-rath02 please review the PR

**Comment by ashutosh-rath02** [comment]
Hey @RamakrushnaBiswal is this design copied from somewhere?

**Comment by RamakrushnaBiswal** [comment]
i just get the svg from online if you want i can change @ashutosh-rath02

**Comment by RamakrushnaBiswal** [comment]
image

**Comment by RamakrushnaBiswal** [comment]
hi @ashutosh-rath02 review the PR

**Comment by RamakrushnaBiswal** [comment]
@ashutosh-rath02 sir add some labels and assign 🙂

**Review by ashutosh-rath02 — COMMENTED** [review]
LGTM

**Pull request merged**
