### PR TITLE
Feat/360

### LINKED ISSUE #360: [Cover Letter]: Multi Step Form Modal
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I am willing to create modal as multi step form to take following parameters as input :
1. Job description
2. Are they willing to add there own resume or we can make use of github resume. They can also add skill, experience, projects....
Finally, generate...

It will also contain form validation and responsiveness.

Let me know if any things to be added.

### Use Case

It will add another feature to our website which will attract users.

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Sid-80**
## Related Issue
resolves #360 

## Description
Added the multi-step form for AI cover letter generation with form validation.

## Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
image
image
image

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by ashutosh-rath02** [comment]
Thank you for submitting your pull request! 🙌 We'll review it as soon as possible. In the meantime, please ensure that your changes align with our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md). If there are any specific instructions or feedback regarding your PR, we'll provide them here. Thanks again for your contribution! 😊

**Comment by ashutosh-rath02** [comment]
@dhairyathedev Would you like to take a look?

**Comment by dhairyathedev** [comment]
It's good @Sid-80.

Few suggestions:
- Give some margin at top.
Screenshot 2024-07-07 at 5 20 38 PM

- Fix the contrast of the steps in light mode
Screenshot 2024-07-07 at 5 23 46 PM


- Fix submit button text contrast
Screenshot 2024-07-07 at 5 22 28 PM

**Comment by Sid-80** [comment]
@dhairyathedev Fixing...

**Comment by Sid-80** [comment]
Changes :

image
image
image
image
image

**Review by ashutosh-rath02 — APPROVED** [review]
LGTM

**Comment by ashutosh-rath02** [comment]
@all-contributors please add @Sid-80 for code

**Pull request merged**
