### PR TITLE
Compare feature (issue6)

### PR DESCRIPTION
**Pull request by Swastik19Nit**
## Related Issue
solves #6 

## Description
Github Profile Comparison

## Type of PR

- [ ] Bug fix
- [X ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

[

https://github.com/ashutosh-rath02/git-re/assets/122457803/854343c4-354c-441e-9962-22867d2c4a67

](url)
## Checklist:
- [ x] I have performed a self-review of my code
- [X ] I have read and followed the Contribution Guidelines.
- [X ] I have tested the changes thoroughly before submitting this pull request.
- [X ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X ] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by ashutosh-rath02** [comment]
Thank you for submitting your pull request! 🙌 We'll review it as soon as possible. In the meantime, please ensure that your changes align with our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md). If there are any specific instructions or feedback regarding your PR, we'll provide them here. Thanks again for your contribution! 😊

**Comment by ashutosh-rath02** [comment]
image
@Swastik19Nit Check for this error.

@dhairyathedev Can you check the component once? And feedbacks are appericiated.

**Comment by ashutosh-rath02** [comment]
image
@Swastik19Nit

**Comment by Swastik19Nit** [comment]
@ashutosh-rath02 sir kindly check again . i have resolved them .

**Comment by ashutosh-rath02** [comment]
@Swastik19Nit Check this 
image

**Comment by ashutosh-rath02** [comment]
Only the graph is looking bad for some user having less interaction otherwise your work is awesome.

**Comment by Swastik19Nit** [comment]
@ashutosh-rath02 i wonder why the web lines are not showing around them.  Can you show me in light mode how this looks? So shall i create differnt radar graphs for both of them?

**Comment by Swastik19Nit** [comment]
Ok i will remove the green shadows. It's not looking good.

**Comment by dhairyathedev** [comment]
> image @Swastik19Nit Check for this error.
> 
> @dhairyathedev Can you check the component once? And feedbacks are appreciated.

@Swastik19Nit before pushing the changes, make sure you run `npm run build` to avoid production build errors.

**Comment by ashutosh-rath02** [comment]
Here you go 
image

**Comment by Swastik19Nit** [comment]
Is type error still happening...though it should not happen?

**Comment by Swastik19Nit** [comment]
Somehow it is not working in dark mode though it should work as it is working in my localhost...only if works in dark mode then it will actually look good

**Comment by ashutosh-rath02** [comment]
Type error is resolved, the image you sent in above message is not visible

**Comment by Swastik19Nit** [comment]
So what should I do now? Help me a little.

**Comment by ashutosh-rath02** [comment]
Can you send the image properly?

**Comment by Swastik19Nit** [comment]
Screenshot_20240629_171838_Chrome
Is it looking that bad? I mean it looks file in the deployed version you sent.

**Comment by Swastik19Nit** [comment]
Fine* ( also i will remove the green shadow)

**Comment by dhairyathedev** [comment]
There is one issue with the suggestions fetching.
Screenshot 2024-06-29 at 5 20 46 PM

**Comment by ashutosh-rath02** [comment]
@Swastik19Nit I guess it was some loading issue now I can see it in dark mode too. One thing you can do to show their individual radar chart and provide option to extrapolate.

**Comment by ashutosh-rath02** [comment]
On clicking compare pass the usernames or some generated string as params because when you refresh it all the data is lost and you have to enter the usernames once again.

**Comment by Swastik19Nit** [comment]
Can you tell me how this issue happened regarding the suggestions? I would have to debug it then . Sorry for disturbing by commenting again and again but what should I do to get this pull request merged? I will create separate radars and remove the green shadow but i wonder what this new issue represents regarding 20 offset signifying?

**Comment by Swastik19Nit** [comment]
Ok i will keep them pass them to avoid their loss.

**Comment by ashutosh-rath02** [comment]
@Swastik19Nit Can you join git-re github channel and we can discuss there?

**Comment by Swastik19Nit** [comment]
Discord?

**Comment by ashutosh-rath02** [comment]
> Discord?

Yeah, it will be in the announcement channel, you can react on git-re and join

**Comment by dhairyathedev** [comment]
Here's the link to the message: https://discord.com/channels/1231112132595028008/1231119005536878612/1240684613530292375

**Comment by ashutosh-rath02** [comment]
LGTM🪨

**Review by ashutosh-rath02 — COMMENTED** [review]
LGTM

**Pull request merged**
