### PR TITLE
[feat]: Leaderboard page

### LINKED ISSUE #242: [Feature Request]: Leaderboard Page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Leaderboard for the resume ratings

### Use Case

Can be used to know how top profiles are created which can be beneficial for the intermediates and beginners profile. Also, motivation for the experts to compete for the top place on the leaderboard.

### Benefits

_No response_

### Add ScreenShots

Screenshot 2024-06-04 at 6 42 55 PM

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by dhairyathedev**
Fixes #242

### CODE REVIEW

**Comment by ashutosh-rath02** [comment]
Thank you for submitting your pull request! 🙌 We'll review it as soon as possible. In the meantime, please ensure that your changes align with our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md). If there are any specific instructions or feedback regarding your PR, we'll provide them here. Thanks again for your contribution! 😊

**Comment by dhairyathedev** [comment]
Demo video: https://youtu.be/5CSQLzbBtXU

**Comment by ashutosh-rath02** [comment]
Can you add the Leaderboard anchor in the navbar?

**Comment by dhairyathedev** [comment]
> Can you add the Leaderboard anchor in the navbar?

#244

**Review by ashutosh-rath02 — COMMENTED** [review]
LGTM

**Pull request merged**
