### PR TITLE
Fixed navbar at top

### PR DESCRIPTION
**Pull request by Utsavladia**
## Related Issue #414 
[Cite any related issue(s) this pull request addresses. If none, simply state “None”]

## Description
Added the navbar at top with fixed padding to get the same view
[Please include a brief description of the changes or features added]

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
image

[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by ashutosh-rath02** [comment]
Thank you for submitting your pull request! 🙌 We'll review it as soon as possible. In the meantime, please ensure that your changes align with our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md). If there are any specific instructions or feedback regarding your PR, we'll provide them here. Thanks again for your contribution! 😊

**Comment by Utsavladia** [comment]
@ashutosh-rath02 
kindly reivew this PR

**Comment by ashutosh-rath02** [comment]
@Utsavladia Please provide a video

**Comment by Utsavladia** [comment]
https://github.com/user-attachments/assets/0fa2dc43-542f-4283-aa9a-c1b904dc0d05

**Comment by ashutosh-rath02** [comment]
Keep the background with some background blur don't make it complete black

**Comment by Utsavladia** [comment]
@ashutosh-rath02 

https://github.com/user-attachments/assets/667ab84a-8ffa-46d3-989e-cbd550491d01

**Comment by Utsavladia** [comment]
@ashutosh-rath02  
or we can make it only blur like this 

https://github.com/user-attachments/assets/b3d8d85c-5d1c-41bf-8ac7-f8241c5ae29d

**Comment by ashutosh-rath02** [comment]
> @ashutosh-rath02 or we can make it only blur like this
> 
>  Recording.2024-08-08.102352.mp4

this one's good

**Comment by Utsavladia** [comment]
@ashutosh-rath02 changed to the blur one ✅

**Comment by Utsavladia** [comment]
@ashutosh-rath02 
Kindly merge this PR before closing of GSSOC 🙂

**Comment by ashutosh-rath02** [comment]
image
@UtsavlaThere's this small gap please correct it as it is looking bad and we are good to go.

**Review by ashutosh-rath02 — APPROVED** [review]
LGTM

**Comment by Utsavladia** [comment]
@ashutosh-rath02 
fixed the gap ✅

**Pull request merged**
