### PR TITLE
DOCS - added table of contents and featured in section

### PR DESCRIPTION
**Pull request by SpaciousCoder78**
Issue: #83 

Added table of contents and featured in section to the readme

image

### CODE REVIEW

**Comment by ashutosh-rath02** [comment]
What about the badges?

**Comment by SpaciousCoder78** [comment]
@ashutosh-rath02 Can you elaborate more on the badges? What kind of badges do you want me to add?

**Comment by ashutosh-rath02** [comment]
nvm @SpaciousCoder78 it's already being done. Good work there. Add a "setup supabase" bullet point and redirect it to learn.md

**Comment by SpaciousCoder78** [comment]
Will do

**Comment by SpaciousCoder78** [comment]
@ashutosh-rath02 Done. Check if everything's ok for you. Tell me if you need any more changes.

**Comment by ashutosh-rath02** [comment]
LGTM🤺

**Comment by ashutosh-rath02** [comment]
@all-contributors please add @SpaciousCoder78 for doc

**Pull request merged**
