### PR TITLE
[Bug]: Profile tracking is not scrollable

### PR DESCRIPTION
**Pull request by Latish705**
## Related Issue
fixes - #282 

## Description
fixed the scrollability of profile tracking  and adding no scroll to background as it was just scrolling the body if try to scroll

## Type of PR

- [x] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

https://github.com/ashutosh-rath02/git-re/assets/104522651/63ee78e0-9ead-49df-8e03-e1827f6d1985

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by ashutosh-rath02** [comment]
Thank you for submitting your pull request! 🙌 We'll review it as soon as possible. In the meantime, please ensure that your changes align with our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md). If there are any specific instructions or feedback regarding your PR, we'll provide them here. Thanks again for your contribution! 😊

**Comment by ashutosh-rath02** [comment]
@Latish705 didn't fix the issue. So removing the tags, please raise another PR

**Comment by Latish705** [comment]
@ashutosh-rath02 working on that , actually when u refresh the page its working that is the issue working on that

**Review by ashutosh-rath02 — COMMENTED** [review]
LGTM

**Pull request merged**
