### PR TITLE
enhancement: update loading state

### LINKED ISSUE #127: enhancement: add skeleton loading to recent users cards
In the current version, the recent user carousel is rendered when the recent users are fetched. Instead, apply the skeleton loading is better idea which improves the user experience.

Skeleton loading demo: https://skeleton-loading-nextjs.vercel.app/

Please assign this issue to me.

### PR DESCRIPTION
**Pull request by dhairyathedev**
### Changelog
- Add skeleton loading for recent users
- Update loading state of login, logout button.

Fixes #127

### CODE REVIEW

**Comment by ashutosh-rath02** [comment]
@dhairyathedev can you provide a short video please

**Comment by ashutosh-rath02** [comment]
Hey @dhairyathedev , you can check out discussion for a new feature discussion https://github.com/ashutosh-rath02/git-re/discussions/133

**Comment by dhairyathedev** [comment]
> @dhairyathedev can you provide a short video please

Here it is @ashutosh-rath02 

https://github.com/ashutosh-rath02/git-re/assets/65452005/5eab852e-9671-45d7-a356-971bccae16d0

**Comment by dhairyathedev** [comment]
Fixed the react hydration error in the above video.

Latest Commit: [1b8b762](https://github.com/ashutosh-rath02/git-re/pull/129/commits/1b8b762a8d55819d2905933de0e7be7ee9e6cd9e)

Screenshot 2024-05-15 at 7 33 10 PM

**Comment by ashutosh-rath02** [comment]
LGTM🤺

**Pull request merged**
