### PR TITLE
enhancement: add top loading animation

### LINKED ISSUE #264: [Feature Request]: Top loading bar animation for page transitions
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Adding a top-loading bar animation can significantly enhance user experience by indicating when a page is loading. This is particularly useful for pages that involve server-side rendering or client-side rendering with preprocessing, where changing the URL path might take some time without any visual feedback. Implementing a top-loading animation bar will ensure smoother page transitions and provide users with clear indicators of loading activity, thereby improving overall user experience.

### Use Case

For better page transition and user experience

### Benefits

Benefits:

- Clear indication of page loading status
- Enhanced perceived performance
- Smoother page transitions

### Add ScreenShots

https://github.com/ashutosh-rath02/git-re/assets/65452005/9bbf6d69-f23d-45cc-9ed8-aceecec03274

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by dhairyathedev**
Fixes #264

### CODE REVIEW

**Comment by ashutosh-rath02** [comment]
Thank you for submitting your pull request! 🙌 We'll review it as soon as possible. In the meantime, please ensure that your changes align with our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md). If there are any specific instructions or feedback regarding your PR, we'll provide them here. Thanks again for your contribution! 😊

**Comment by ashutosh-rath02** [comment]
you can remove the `bun.lockb` file

**Comment by dhairyathedev** [comment]
Done @ashutosh-rath02

**Review by ashutosh-rath02 — COMMENTED** [review]
LGTM

**Pull request merged**
