### PR TITLE
added margin to FAQ section

### PR DESCRIPTION
**Pull request by K-kiran77**
## Related Issue
My issue number is #393

## Description
I have added some margin to the FAQ section, previously on mobile screen the section was overflowing the screen and content was hiding

## Type of PR

- [ X] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
Previously FAQ section was looking like this 
WhatsApp Image 2024-07-20 at 07 46 10
After adding margin the section is looking like this 
FAQ section after

## Checklist:
- [ X] I have performed a self-review of my code
- [X ] I have read and followed the Contribution Guidelines.
- [ X] I have tested the changes thoroughly before submitting this pull request.
- [X ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by ashutosh-rath02** [comment]
Thank you for submitting your pull request! 🙌 We'll review it as soon as possible. In the meantime, please ensure that your changes align with our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md). If there are any specific instructions or feedback regarding your PR, we'll provide them here. Thanks again for your contribution! 😊

**Review by ashutosh-rath02 — CHANGES_REQUESTED** [review]
Make the text left aligned please

**Comment by K-kiran77** [comment]
I have made the text aligned to left, Kindly review my change

**This is screenshot after the change**
git-re faq

**Comment by ashutosh-rath02** [comment]
@K-kiran77 there are some unwanted changes in your PR please revert that.

**Comment by ashutosh-rath02** [comment]
Can you revert deletion of .env.example?

**Review by ashutosh-rath02 — APPROVED** [review]

**Pull request merged**
