### PR TITLE
Recent profiles

### PR DESCRIPTION
**Pull request by RoopsagarK**
Added the recent profile generations section just below the hero section. I kindly request a review of my code and appreciate any further suggestions for improvement.
(GSSOC'24)

### CODE REVIEW

**Comment by RoopsagarK** [comment]
https://github.com/ashutosh-rath02/git-re/assets/107497296/f62f9e0b-8bc9-4fe4-99c8-aeac78eb6740

Here is the video of the section!

**Comment by ashutosh-rath02** [comment]
@RoopsagarK Please remove the changes in all-contributorsrc . I will do those changes. Can you please contact me over discord? Have a few things to discuss😊. My username `.vasudev`

**Comment by ashutosh-rath02** [comment]
I cannot see the component in the preview. I also have a few more suggestions please reach out to me on discord.

**Comment by RoopsagarK** [comment]
@ashutosh-rath02. I've sent you a message on Discord. Could you please check it

**Comment by ashutosh-rath02** [comment]
LGTM.🚀

**Comment by ashutosh-rath02** [comment]
@all-contributors please add @RoopsagarK  for code

**Pull request merged**
