### PR TITLE
Login Btn Changed #42

### PR DESCRIPTION
**Pull request by rishabh-bijalwan12**
fixes#42
 

changed the UI of login and logout btn and added scale property to the footer at linkedin,twitter and github icon

login btn

Screenshot 2024-05-11 155336

footer icon 

Screenshot 2024-05-11 155431

### CODE REVIEW

**Comment by rishabh-bijalwan12** [comment]
let me know if you want any changes

**Comment by ashutosh-rath02** [comment]
The button isn't looking good. Can you provide some other designs?

**Comment by rishabh-bijalwan12** [comment]
sure

**Comment by rishabh-bijalwan12** [comment]
Now i taken the same color for btn but added same theme color on text of btn on hovering which make it more professional and user friendly now on hovering on each text on navbar give same color like fork and login

**Comment by rishabh-bijalwan12** [comment]
Now i taken the same color of btn as it was before but added color to the  text of login btn which match the theme of your website now both fork  text and login text on hover  have same color

should i delete this pr and create new one? or any suggestion

Screenshot 2024-05-11 180213

**Comment by ashutosh-rath02** [comment]
> Now i taken the same color of btn as it was before but added color to the text of login btn which match the theme of your website now both fork text and login text on hover have same color
> 
> should i delete this pr and create new one? or any suggestion
> 
> Screenshot 2024-05-11 180213

Keep the text color white and on hover you can change it to some grayish color. The blue color isnt looking good

**Pull request closed without merging**
