### PR TITLE
fixed: recent users error handling and loading state 

### LINKED ISSUE #121: bug: public.recent_users null check/adding error handling
Apparently there is no null check for recent.users fetching from supabase which is showing error if not users are present in recent.users.

I want to add a error handling instead of throwing error, here so that app works seamless.

image
@ashutosh-rath02

### PR DESCRIPTION
**Pull request by ratishjain12**
@ashutosh-rath02 

fixes #121 

added loading state in recent users section and now it will not throw error if recent users does not exist

https://github.com/ashutosh-rath02/git-re/assets/43003421/bf0ce7fc-9fe3-42a1-b945-2d683db906b7

### CODE REVIEW

**Comment by ratishjain12** [comment]
@ashutosh-rath02 do check this out and merge it if everything looks good

**Comment by ashutosh-rath02** [comment]
@ratishjain12 I think you haven't pushed the changes

**Comment by ratishjain12** [comment]
> @ratishjain12 I think you haven't pushed the changes

aight its done

**Comment by ashutosh-rath02** [comment]
Hey @ratishjain12 move it to public folder

**Comment by ashutosh-rath02** [comment]
Hey @ratishjain12 , you can check out discussion for a new feature discussion https://github.com/ashutosh-rath02/git-re/discussions/133

**Pull request merged**
