### PR TITLE
For avoiding workflow failure

### PR DESCRIPTION
**Pull request by Asymtode712**
@ashutosh-rath02 This commit should resolve the workflow failure for closing old PRs, please review and merge this PR

### CODE REVIEW

**Comment by ashutosh-rath02** [comment]
Why it's changed to GITHUB_TOKEN?

**Comment by Asymtode712** [comment]
Because GITHUB_TOKEN is a built-in secret provided by GitHub Actions which is automatically generated by GitHub for each workflow run. It provides appropriate permissions to perform tasks within the repository, like this one.

**Comment by ashutosh-rath02** [comment]
Then remove all occurence of MY_SECRET_TOKEN in the pr?

**Comment by Asymtode712** [comment]
No just for this PR

**Comment by Asymtode712** [comment]
@ashutosh-rath02 You merge this PR and lets test the workflow

**Pull request merged**
