### PR TITLE
 Updated hover effect of buttons. 

### PR DESCRIPTION
**Pull request by Rakshit-gen**
Changed the colour upon hover to light grey.

### CODE REVIEW

**Comment by ashutosh-rath02** [comment]
Hey @Rakshit-gen Can you please add a before and after screenshot.

**Comment by Rakshit-gen** [comment]
Sure wait

**Comment by Rakshit-gen** [comment]
Wait I can't do it because I don't have the environment variables which you can't share obviously @ashutosh-rath02

**Comment by ashutosh-rath02** [comment]
Why can't you check buttons hover?

**Comment by Rakshit-gen** [comment]
Because on my local device it's telling me that there are no env variables so it can't run
And even when I'm trying to host it

How do I check the buttons hover properly without hosting and all that? @ashutosh-rath02

**Comment by ashutosh-rath02** [comment]
> Because on my local device it's telling me that there are no env variables so it can't run And even when I'm trying to host it
> 
> How do I check the buttons hover properly without hosting and all that? @ashutosh-rath02

Hover button is on home page you need not any env variables to make it work

**Comment by Rakshit-gen** [comment]
It won't work @ashutosh-rath02 I've tried it's just showing an error saying that without supabase etc it won't work

**Comment by ashutosh-rath02** [comment]
You can see the Button component being repeated twice, can you optimize the code? Then we are gtg. I checked the change @Rakshit-gen

**Comment by Rakshit-gen** [comment]
Wait give me some time I'd do it @ashutosh-rath02

**Comment by SiddharthaArepalli** [comment]
@ashutosh-rath02  I can work on that

**Comment by ashutosh-rath02** [comment]
@Rakshit-gen any update?

**Comment by Rakshit-gen** [comment]
Actually @ashutosh-rath02 I'm travelling rn that's why I asked for time. I'm going back to home and it would take me till tommorow to start my work.

Thank you!

**Comment by SiddharthaArepalli** [comment]
@ashutosh-rath02 I can work on it !!

**Comment by ashutosh-rath02** [comment]
@SiddharthaArepalli Currently you can work on the UI design. We will come to this further. Let @Rakshit-gen work on it😊

**Comment by ashutosh-rath02** [comment]
@Rakshit-gen Updates?

**Comment by Rakshit-gen** [comment]
Hey @ashutosh-rath02 im actually travelling rn as I told you. I have a vacation of 2.5 months so I'm visiting home. I would start the work as soon as I reach my home and I'd complete it tommorow evening. Sorry for the late work!

**Comment by ashutosh-rath02** [comment]
Outdated

**Pull request closed without merging**
