### PR TITLE
added logo and changed favicon.

### PR DESCRIPTION
**Pull request by sweta-singh28**
## Related Issue
added logo and changed favicon.

#issue no. #409 

## Description
Updated the logo and changed the favicon to enhance the project's appearance, giving it a more modern and cohesive visual identity. These changes aim to create a more polished look and improve user recognition and experience.

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

Screenshot 2024-08-02 215008

Screenshot 2024-08-02 215023

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by ashutosh-rath02** [comment]
Thank you for submitting your pull request! 🙌 We'll review it as soon as possible. In the meantime, please ensure that your changes align with our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md). If there are any specific instructions or feedback regarding your PR, we'll provide them here. Thanks again for your contribution! 😊

**Comment by sweta-singh28** [comment]
@ashutosh-rath02 sir, done.

**Comment by ashutosh-rath02** [comment]
It isn't looking good tbh.

**Comment by sweta-singh28** [comment]
sir @ashutosh-rath02 could you please tell me what would you expect from the new logo, like something specific that you would want.

**Comment by sweta-singh28** [comment]
@ashutosh-rath02 sir,  could you please review these drafts and please select one of these or if none are viable please tell me so.

1. 
Default_Create_a_simple_yet_informative_logo_for_a_web_applica_0-removebg-preview (1)
 
2. 
Default_Create_a_simple_yet_informative_logo_for_a_web_applica_1__1_-removebg-preview (1)

 3. 
Default_Create_a_simple_yet_informative_logo_for_a_web_applica_1__2_-removebg-preview

4. 
Default_Create_a_simple_yet_informative_logo_for_a_web_applica_1__3_-removebg-preview (1)

5.
Default_Create_a_simple_yet_informative_logo_for_a_web_applica_1-removebg-preview (1)

**Comment by sweta-singh28** [comment]
@ashutosh-rath02 sir

**Comment by ashutosh-rath02** [comment]
@sweta-singh28 Are you designing these or generating from somewhere?
It ain't looking good with the text and color scheme

**Comment by sweta-singh28** [comment]
@ashutosh-rath02 sir, I have generated these images and then edited them in order to fit them perfectly into your project and made sure it matches the blue black theme with the minimalist and modern design. Currently these app doesn't have any logo and only uses its names in order to convey the project which doesn't represent it correctly where as the logo I generated tend to do that work as it contains components displaying resume and the favicon displaying the of github.

**Comment by sweta-singh28** [comment]
@ashutosh-rath02 sir

**Comment by ashutosh-rath02** [comment]
@sweta-singh28 Logo is an important feature of any product so I need to ensure it looks pretty well. These logos aren't looking good to me, so I am stalling this issue for now. Thanks for contributing.

**Pull request closed without merging**
